In [2]:
import pandas as pd
from pathlib import Path

POS_PATH = Path("/media/auk/projects/gak76/vira_beg_outputs/training_data/positives/positive_vira_1s_gk.pkl")
XC_PATH = Path("/media/auk/projects/gak76/vira_beg_outputs/training_data/negative_multihot_labels_gk.pkl")
FIELD_PATH = Path("/media/auk/projects/gak76/vira_beg_outputs/training_data/field_negatives/field_negatives_gk.pkl")

pos_df = pd.read_pickle(POS_PATH)
xc_df = pd.read_pickle(XC_PATH)
field_df = pd.read_pickle(FIELD_PATH)

print("POSITIVES")
print(type(pos_df))
print(pos_df.shape)
print(pos_df.columns if hasattr(pos_df, "columns") else "no columns")
display(pos_df.head())

print("\nXC")
print(type(xc_df))
print(xc_df.shape)
print(xc_df.columns if hasattr(xc_df, "columns") else "no columns")
display(xc_df.head())

print("\nFIELD")
print(type(field_df))
print(field_df.shape)
print(field_df.columns if hasattr(field_df, "columns") else "no columns")
display(field_df.head())

POSITIVES
<class 'pandas.core.frame.DataFrame'>
(273, 1)
Index(['virail'], dtype='object')

                                                                        virail
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       1
                                                   0.876813   1.876813       1
                                                   2.164027   3.164027       1
                                                   3.380698   4.380698       1
                                                   4.314080   5.314080       1

XC
<class 'pandas.core.frame.DataFrame'>
(62966, 30)
Index(['sora', 'kinrai4', 'sancra', 'horgre', 'comgal1', 'y00475', 'pibgre',
       'killde', 'sposan', 'ribgul', 'amhgul1', 'rethaw', 'reshaw', 'easpho',
       'eawpew', 'easkin', 'wilfly', 'reevir1', 'blujay', 'comgra', 'rusbla',
       'comyel', 'yelwar1', 'grycat', 'bkcchi', 'rewbla', 'marwre', 'sonspa',
       'swaspa', 'cedwax'],
      dtype='object')

                                                               sora  kinrai4  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016          1        0
                                                   2.832          1        0
                                                   2.944          1        0
                                                   5.744          1        0
                                                   7.840          1        0

                                                               sancra  horgre  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0       0
                                                   2.832            0       0
                                                   2.944            0       0
                                                   5.744            0       0
                                                   7.840            0       0

                                                               comgal1  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016             0
                                                   2.832             0
                                                   2.944             0
                                                   5.744             0
                                                   7.840             0

                                                               y00475  pibgre  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0       0
                                                   2.832            0       0
                                                   2.944            0       0
                                                   5.744            0       0
                                                   7.840            0       0

                                                               killde  sposan  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0       0
                                                   2.832            0       0
                                                   2.944            0       0
                                                   5.744            0       0
                                                   7.840            0       0

                                                               ribgul  ...  \
file                                               start_time          ...
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0  ...
                                                   2.832            0  ...
                                                   2.944            0  ...
                                                   5.744            0  ...
                                                   7.840            0  ...

                                                               rusbla  comyel  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0       0
                                                   2.832            0       0
                                                   2.944            0       0
                                                   5.744            0       0
                                                   7.840            0       0

                                                               yelwar1  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016             0
                                                   2.832             0
                                                   2.944             0
                                                   5.744             0
                                                   7.840             0

                                                               grycat  bkcchi  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0       0
                                                   2.832            0       0
                                                   2.944            0       0
                                                   5.744            0       0
                                                   7.840            0       0

                                                               rewbla  marwre  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0       0
                                                   2.832            0       0
                                                   2.944            0       0
                                                   5.744            0       0
                                                   7.840            0       0

                                                               sonspa  swaspa  \
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0       0
                                                   2.832            0       0
                                                   2.944            0       0
                                                   5.744            0       0
                                                   7.840            0       0

                                                               cedwax
file                                               start_time
/media/kiwi/datasets/annotated/xeno_canto_snaps... 0.016            0
                                                   2.832            0
                                                   2.944            0
                                                   5.744            0
                                                   7.840            0

[5 rows x 30 columns]

FIELD
<class 'pandas.core.frame.DataFrame'>
(29700, 4)
Index(['file', 'start_time', 'end_time', 'field_data'], dtype='object')

,file,start_time,end_time,field_data
0,/media/kiwi/datasets/unfinalized/rloc2025a/MSD...,0.0,1.0,1
1,/media/kiwi/datasets/unfinalized/rloc2025a/MSD...,1.0,2.0,1
2,/media/kiwi/datasets/unfinalized/rloc2025a/MSD...,2.0,3.0,1
3,/media/kiwi/datasets/unfinalized/rloc2025a/MSD...,3.0,4.0,1
4,/media/kiwi/datasets/unfinalized/rloc2025a/MSD...,4.0,5.0,1

In [3]:
MERGE_DIR = Path("/media/auk/projects/gak76/vira_beg_outputs/training_data/fulltrain")
MERGE_DIR.mkdir(parents=True, exist_ok=True)

pos_df = pd.read_pickle(POS_PATH)
xc_df = pd.read_pickle(XC_PATH)
field_df = pd.read_pickle(FIELD_PATH)

print("Loaded:")
print("positives:", pos_df.shape)
print("xc:", xc_df.shape)
print("field:", field_df.shape)

# ----------------------------
# normalize positives
# ----------------------------
if isinstance(pos_df.index, pd.MultiIndex):
    pos_df = pos_df.reset_index()

pos_df["virail"] = 1

# ----------------------------
# normalize XC negatives
# ----------------------------
if isinstance(xc_df.index, pd.MultiIndex):
    xc_df = xc_df.reset_index()

xc_df["virail"] = 0

if "end_time" not in xc_df.columns and "start_time" in xc_df.columns:
    xc_df["end_time"] = xc_df["start_time"] + 1.0

# ----------------------------
# merge positives + XC
# ----------------------------
main_cols = sorted(set(pos_df.columns) | set(xc_df.columns))
for col in main_cols:
    if col not in pos_df.columns:
        pos_df[col] = 0
    if col not in xc_df.columns:
        xc_df[col] = 0

pos_df = pos_df[main_cols]
xc_df = xc_df[main_cols]

main_df = pd.concat([pos_df, xc_df], ignore_index=True).fillna(0)

# ----------------------------
# normalize field negatives
# ----------------------------
if isinstance(field_df.index, pd.MultiIndex):
    field_df = field_df.reset_index()

if "full_path" in field_df.columns and "file" not in field_df.columns:
    field_df = field_df.rename(columns={"full_path": "file"})

field_df["virail"] = 0
field_df["field_data"] = 1

if "end_time" not in field_df.columns and "start_time" in field_df.columns:
    field_df["end_time"] = field_df["start_time"] + 1.0

# ----------------------------
# align columns and append field negatives
# ----------------------------
all_cols = sorted(set(main_df.columns) | set(field_df.columns))
for col in all_cols:
    if col not in main_df.columns:
        main_df[col] = 0
    if col not in field_df.columns:
        field_df[col] = 0

main_df = main_df[all_cols]
field_df = field_df[all_cols]

full_df = pd.concat([main_df, field_df], ignore_index=True).fillna(0)

# ----------------------------
# final OpenSoundscape format
# ----------------------------
full_df = full_df.set_index(["file", "start_time", "end_time"]).sort_index()

print("Final full dataset shape:", full_df.shape)
display(full_df.head())

full_df.to_pickle(MERGE_DIR / "full_dataset_1s_gk.pkl")
print("Saved to:", MERGE_DIR / "full_dataset_1s_gk.pkl")

Loaded:
positives: (273, 1)
xc: (62966, 30)
field: (29700, 4)
Final full dataset shape: (92939, 32)

                                                                        amhgul1  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303        0
                                                   0.876813   1.876813        0
                                                   2.164027   3.164027        0
                                                   3.380698   4.380698        0
                                                   4.314080   5.314080        0

                                                                        bkcchi  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        blujay  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        cedwax  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        comgal1  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303        0
                                                   0.876813   1.876813        0
                                                   2.164027   3.164027        0
                                                   3.380698   4.380698        0
                                                   4.314080   5.314080        0

                                                                        comgra  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        comyel  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        easkin  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        easpho  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        eawpew  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        ...  \
file                                               start_time end_time  ...
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303  ...
                                                   0.876813   1.876813  ...
                                                   2.164027   3.164027  ...
                                                   3.380698   4.380698  ...
                                                   4.314080   5.314080  ...

                                                                        rusbla  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        sancra  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        sonspa  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        sora  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303     0
                                                   0.876813   1.876813     0
                                                   2.164027   3.164027     0
                                                   3.380698   4.380698     0
                                                   4.314080   5.314080     0

                                                                        sposan  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        swaspa  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        virail  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       1
                                                   0.876813   1.876813       1
                                                   2.164027   3.164027       1
                                                   3.380698   4.380698       1
                                                   4.314080   5.314080       1

                                                                        wilfly  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        y00475  \
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303       0
                                                   0.876813   1.876813       0
                                                   2.164027   3.164027       0
                                                   3.380698   4.380698       0
                                                   4.314080   5.314080       0

                                                                        yelwar1
file                                               start_time end_time
/home/brg226/projects/vira_beg/training_data/an... 0.378303   1.378303        0
                                                   0.876813   1.876813        0
                                                   2.164027   3.164027        0
                                                   3.380698   4.380698        0
                                                   4.314080   5.314080        0

[5 rows x 32 columns]

Saved to: /media/auk/projects/gak76/vira_beg_outputs/training_data/fulltrain/full_dataset_1s_gk.pkl